server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/postgres?user=${POSTGRE_USERNAME}&password=${POSTGRE_PASSWORD}
    username: ${POSTGRE_USERNAME}
    password: ${POSTGRE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update





