server:
  port: 8015

spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/bookrestaurant
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver


  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update




